DROP TABLE IF EXISTS TARJETA;

CREATE TABLE TARJETA(
MARCA VARCHAR(4) NOT NULL,
NUMERO VARCHAR(16) NOT NULL,
CARDHOLDER VARCHAR(200) NOT NULL,
FECHAVENCIMIENTO VARCHAR(5) NOT NULL,
PRIMARY KEY(NUMERO)
);